<?php

namespace Database\Seeders;

use App\Models\PortfolioProject;
use Illuminate\Database\Seeder;

class PortfolioProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            ['cat' => 'pipeline', 'year' => 2024, 'name' => 'Jaringan Distribusi Gas Industri Karawang Fase 2', 'location' => 'Karawang, Jawa Barat', 'client' => 'PT. KIE / PGN', 'scale' => 3, 'specs' => ['45 km pipa', 'MDPE & CS', '6 bar MAOP'], 'status' => 'ongoing', 'icon' => 'ti-line-dashed', 'color' => '#042C53', 'bg_light' => '#E6F1FB', 'accent_text' => '#0C447C', 'stats' => ['45 km', '6 bar', '2024–2025'], 'stat_labels' => ['Panjang Pipa', 'Tekanan', 'Periode'], 'scope' => ['FEED & detailed engineering', 'Pengadaan pipa MDPE PE100', 'Instalasi & pengelasan', 'Pressure test & komisioning', 'Interfacing dengan jaringan PGN'], 'highlights' => ['Jaringan distribusi kawasan industri terbesar di Karawang', 'Melayani 120+ pelanggan industri', 'Integrasi SCADA real-time monitoring']],
            ['cat' => 'cng', 'year' => 2023, 'name' => 'SPBG Bekasi Timur — Kapasitas 500 MMBtu/hari', 'location' => 'Bekasi, Jawa Barat', 'client' => 'PT. Trans Bekasi Mandiri', 'scale' => 4, 'specs' => ['500 MMBtu/hari', '250 bar filling', 'Dual dispenser'], 'status' => 'done', 'icon' => 'ti-gas-station', 'color' => '#854F0B', 'bg_light' => '#FAEEDA', 'accent_text' => '#633806', 'stats' => ['500', '250 bar', '4 unit'], 'stat_labels' => ['MMBtu/hari', 'Tekanan Isi', 'Dispenser'], 'scope' => ['Engineering & design SPBG', 'Pengadaan compressor & storage', 'Instalasi mekanikal & elektrikal', 'Commissioning & uji operasional', 'Pendampingan sertifikasi BPH MIGAS'], 'highlights' => ['SPBG terbesar di Bekasi Timur', 'Melayani 300+ kendaraan CNG/hari', 'Teknologi fast-fill & slow-fill']],
            ['cat' => 'pipeline', 'year' => 2023, 'name' => 'Pipa Transmisi Gas Bumi Cilegon–Serang', 'location' => 'Banten', 'client' => 'Pemprov Banten / PGN', 'scale' => 5, 'specs' => ['120 km', 'API 5L X60', '40 bar MAOP'], 'status' => 'done', 'icon' => 'ti-line-dashed', 'color' => '#042C53', 'bg_light' => '#E6F1FB', 'accent_text' => '#0C447C', 'stats' => ['120 km', '40 bar', '18 bln'], 'stat_labels' => ['Panjang', 'Tekanan', 'Durasi'], 'scope' => ['Survei rute & AMDAL', 'FEED & DED transmisi', 'Pengadaan pipa API 5L X60', 'Pengelasan & coating 3LPE', 'HDD crossing jalan tol & sungai', 'Hydrostatic test & komisioning'], 'highlights' => ['Proyek transmisi terpanjang yang pernah dikerjakan', '3 titik river crossing & 2 road crossing', 'Coating 3LPE anti-korosi premium']],
            ['cat' => 'cng', 'year' => 2023, 'name' => 'Virtual Pipeline CNG Kawasan Industri Purwakarta', 'location' => 'Purwakarta, Jawa Barat', 'client' => 'PT. KIIC Purwakarta', 'scale' => 2, 'specs' => ['12 truk CNG', '200 bar', '30 MMBtu/hari'], 'status' => 'done', 'icon' => 'ti-truck', 'color' => '#854F0B', 'bg_light' => '#FAEEDA', 'accent_text' => '#633806', 'stats' => ['12 unit', '200 bar', '30 MMBtu'], 'stat_labels' => ['Armada Truk', 'Tekanan', 'Kapasitas/hari'], 'scope' => ['Desain sistem virtual pipeline', 'Pengadaan tube trailer CNG', 'Instalasi metering & regulasi di pabrik', 'Pelatihan operator', 'SOP operasional & safety'], 'highlights' => ['Solusi gas untuk area belum terjangkau pipa', 'Pengiriman just-in-time ke 8 pabrik', 'Penghematan energi 35% vs LPG']],
            ['cat' => 'maintenance', 'year' => 2023, 'name' => 'Inspeksi & Rehabilitasi Pipeline PGN Bekasi–Cikampek', 'location' => 'Jawa Barat', 'client' => 'PT. PGN Tbk', 'scale' => 3, 'specs' => ['80 km ILI', 'MFL Tool', 'Cathodic Protection'], 'status' => 'done', 'icon' => 'ti-settings-2', 'color' => '#27500A', 'bg_light' => '#EAF3DE', 'accent_text' => '#3B6D11', 'stats' => ['80 km', '6 titik', '100%'], 'stat_labels' => ['Panjang ILI', 'Anomali Kritis', 'Selesai Tepat Waktu'], 'scope' => ['Intelligent pig launching & receiving', 'MFL inspection & data analysis', 'Excavation & repair 6 titik anomali', 'Penggantian cathodic protection anode', 'Laporan integritas pipeline'], 'highlights' => ['Zero incident selama pekerjaan', '6 titik korosi berhasil direhabilitasi', 'Laporan ILI sesuai ASME B31.8S']],
            ['cat' => 'engineering', 'year' => 2022, 'name' => 'FEED & DED SPBG Mother Station Cikarang', 'location' => 'Bekasi, Jawa Barat', 'client' => 'PT. Cikarang Energi', 'scale' => 2, 'specs' => ['DED lengkap', 'HAZOP study', 'BOQ & tender'], 'status' => 'done', 'icon' => 'ti-chart-dots-2', 'color' => '#085041', 'bg_light' => '#E1F5EE', 'accent_text' => '#0F6E56', 'stats' => ['1.000', '4 bln', '100%'], 'stat_labels' => ['MMBtu Rancangan', 'Durasi FEED', 'Akurasi Dokumen'], 'scope' => ['Conceptual design & feasibility', 'Front End Engineering Design', 'Process flow diagram & P&ID', 'HAZOP & SIL assessment', 'Bill of Quantity & dokumen tender'], 'highlights' => ['Desain mother station kapasitas 1.000 MMBtu/hari', 'Dokumen tender digunakan langsung oleh owner', 'Proses approval BPH MIGAS hanya 3 bulan']],
            ['cat' => 'pipeline', 'year' => 2022, 'name' => 'Gas Distribution Network Kawasan Industri MM2100', 'location' => 'Bekasi, Jawa Barat', 'client' => 'PT. MM2100 Industrial Town', 'scale' => 4, 'specs' => ['35 km', 'Low–Medium pressure', '50+ pelanggan'], 'status' => 'done', 'icon' => 'ti-line-dashed', 'color' => '#042C53', 'bg_light' => '#E6F1FB', 'accent_text' => '#0C447C', 'stats' => ['35 km', '52', '2022'], 'stat_labels' => ['Panjang Jaringan', 'Pelanggan Industri', 'Selesai'], 'scope' => ['Master plan jaringan gas kawasan', 'Engineering & procurement', 'Instalasi jaringan LP & MP', 'Pemasangan metering station tiap pabrik', 'Komisioning & serah terima'], 'highlights' => ['Melayani 52 pabrik multinasional', 'Sistem metering individual per pelanggan', 'Backup supply CNG terintegrasi']],
            ['cat' => 'cng', 'year' => 2022, 'name' => 'Daughter Station CNG Armada Bus TransJakarta Rute Barat', 'location' => 'Jakarta Barat', 'client' => 'PT. Transjakarta', 'scale' => 3, 'specs' => ['300 MMBtu/hari', 'Daughter Station', '8 dispenser'], 'status' => 'done', 'icon' => 'ti-gas-station', 'color' => '#854F0B', 'bg_light' => '#FAEEDA', 'accent_text' => '#633806', 'stats' => ['300', '8 unit', '200+'], 'stat_labels' => ['MMBtu/hari', 'Dispenser', 'Bus/hari'], 'scope' => ['Engineering daughter station', 'Pengadaan storage cascade & dispenser', 'Instalasi sistem safety & CCTV', 'Commissioning & uji beban', 'Pelatihan teknisi Transjakarta'], 'highlights' => ['Mendukung program bus ramah lingkungan DKI', 'Kapasitas pengisian 200+ bus CNG per hari', 'Sistem monitoring real-time terintegrasi']],
            ['cat' => 'pipeline', 'year' => 2021, 'name' => 'City Gas Distribution Kota Cirebon Fase 1', 'location' => 'Cirebon, Jawa Barat', 'client' => 'PGN / Pemkot Cirebon', 'scale' => 3, 'specs' => ['28 km', 'PE80/100', 'Rumah tangga'], 'status' => 'done', 'icon' => 'ti-home', 'color' => '#042C53', 'bg_light' => '#E6F1FB', 'accent_text' => '#0C447C', 'stats' => ['28 km', '4.200', '2021'], 'stat_labels' => ['Jaringan HDPE', 'Sambungan Rumah', 'Selesai'], 'scope' => ['Desain jaringan city gas', 'Instalasi pipa HDPE PE80/100', 'Pemasangan regulator & metering rumah', 'Uji kebocoran & komisioning', 'Pelatihan operator kota'], 'highlights' => ['4.200 sambungan rumah tangga aktif', 'Pengurangan emisi LPG di Cirebon', 'Program pemerintah strategis nasional']],
            ['cat' => 'maintenance', 'year' => 2021, 'name' => 'Perawatan Tahunan Sistem Gas PT. Chandra Asri Petrochemical', 'location' => 'Cilegon, Banten', 'client' => 'PT. Chandra Asri Petrochemical', 'scale' => 3, 'specs' => ['Kontrak 3 tahun', 'Pigging rutin', 'Valve maintenance'], 'status' => 'ongoing', 'icon' => 'ti-settings-2', 'color' => '#27500A', 'bg_light' => '#EAF3DE', 'accent_text' => '#3B6D11', 'stats' => ['3 tahun', '15 km', '24/7'], 'stat_labels' => ['Kontrak', 'Pipa Dirawat', 'Siaga Emergency'], 'scope' => ['Pemeliharaan preventif bulanan', 'Pigging & pembersihan pipa', 'Kalibrasi metering & instrument', 'Penggantian valve & gasket', 'Laporan kondisi & rekomendasi'], 'highlights' => ['Kontrak jangka panjang 3 tahun', 'Zero unplanned shutdown sejak kontrak', 'Tim resident engineer di lokasi']],
            ['cat' => 'engineering', 'year' => 2020, 'name' => 'Studi Kelayakan Pipeline Gas Sumatera Selatan', 'location' => 'Sumatera Selatan', 'client' => 'Pemerintah Provinsi Sumsel', 'scale' => 2, 'specs' => ['200 km rencana', 'Feasibility Study', 'ROI analysis'], 'status' => 'done', 'icon' => 'ti-chart-dots-2', 'color' => '#085041', 'bg_light' => '#E1F5EE', 'accent_text' => '#0F6E56', 'stats' => ['200 km', '6 bln', '2020'], 'stat_labels' => ['Panjang Rencana', 'Durasi Studi', 'Selesai'], 'scope' => ['Studi kelayakan teknis & ekonomis', 'Survei kondisi lapangan', 'Analisis rute & topografi', 'Estimasi CAPEX & OPEX', 'Rekomendasi skema pembiayaan'], 'highlights' => ['Studi menjadi dasar program infrastruktur provinsi', 'Potensi investasi Rp 2,4 Triliun teridentifikasi', 'Presentasi ke Kementerian ESDM']],
            ['cat' => 'cng', 'year' => 2020, 'name' => 'Mobile Refueling Unit (MRU) Armada Tambang Kaltim', 'location' => 'Kutai Kartanegara, Kalimantan Timur', 'client' => 'PT. Kideco Jaya Agung', 'scale' => 3, 'specs' => ['5 unit MRU', '200 bar', 'Alat berat CNG'], 'status' => 'done', 'icon' => 'ti-truck', 'color' => '#854F0B', 'bg_light' => '#FAEEDA', 'accent_text' => '#633806', 'stats' => ['5 unit', '200 bar', '60 unit'], 'stat_labels' => ['MRU', 'Tekanan Isi', 'Alat Berat Dilayani'], 'scope' => ['Desain sistem MRU untuk tambang', 'Pengadaan compressor mobile', 'Konversi alat berat ke CNG', 'Pelatihan operator & mekanik', 'SOP operasional area tambang'], 'highlights' => ['Pertama di Indonesia untuk alat berat tambang batubara', 'Penghematan bahan bakar 40% vs HSD', 'Sertifikat K3 alat berat dari Kemnaker']],
        ];

        foreach ($projects as $i => $project) {
            PortfolioProject::query()->updateOrCreate(
                ['name' => $project['name']],
                [...$project, 'sort_order' => $i],
            );
        }
    }
}
